import { Routes } from '@angular/router';
import { Landing } from './pages/landing/landing';
import { ServiceDetails } from './pages/service-details/service-details';
import { CategoriesPage } from './pages/categories-page/categories-page';
import { ContactPage } from './pages/contact-page/contact-page';
import { LocationsPage } from './pages/locations-page/locations-page';
import { ProjectsPage } from './pages/projects-page/projects-page';
import { ProjectDetails } from './pages/project-details/project-details';
import { PrivacyPolicyPage } from './pages/privacy-policy-page/privacy-policy-page';
import { TermsConditionsPage } from './pages/terms-conditions-page/terms-conditions-page';
import { FaqPage } from './pages/faq-page/faq-page';

export const routes: Routes = [
  { path: '', component: Landing },
  { path: 'categories', component: CategoriesPage },
  { path: 'projects', component: ProjectsPage },
  { path: 'projects/:id', component: ProjectDetails },
  { path: 'project-details', component: ProjectDetails },
  { path: 'project-details/:id', component: ProjectDetails },
  { path: 'contact', component: ContactPage },
  { path: 'locations', component: LocationsPage },
  { path: 'locations/:city', component: LocationsPage },
  { path: 'service-details', component: ServiceDetails },
  { path: 'service-details/:slug', component: ServiceDetails },
  { path: 'services', component: ServiceDetails },
  { path: 'services/:slug', component: ServiceDetails },
  { path: 'privacy-policy', component: PrivacyPolicyPage },
  { path: 'terms-conditions', component: TermsConditionsPage },
  { path: 'faq', component: FaqPage },
  { path: '**', redirectTo: '' }
];
